// Generated by gencpp from file action_quiz/CustomActionMsgGoal.msg
// DO NOT EDIT!


#ifndef ACTION_QUIZ_MESSAGE_CUSTOMACTIONMSGGOAL_H
#define ACTION_QUIZ_MESSAGE_CUSTOMACTIONMSGGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_quiz
{
template <class ContainerAllocator>
struct CustomActionMsgGoal_
{
  typedef CustomActionMsgGoal_<ContainerAllocator> Type;

  CustomActionMsgGoal_()
    : goal()  {
    }
  CustomActionMsgGoal_(const ContainerAllocator& _alloc)
    : goal(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::action_quiz::CustomActionMsgGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_quiz::CustomActionMsgGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CustomActionMsgGoal_

typedef ::action_quiz::CustomActionMsgGoal_<std::allocator<void> > CustomActionMsgGoal;

typedef boost::shared_ptr< ::action_quiz::CustomActionMsgGoal > CustomActionMsgGoalPtr;
typedef boost::shared_ptr< ::action_quiz::CustomActionMsgGoal const> CustomActionMsgGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_quiz::CustomActionMsgGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_quiz::CustomActionMsgGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_quiz::CustomActionMsgGoal_<ContainerAllocator1> & lhs, const ::action_quiz::CustomActionMsgGoal_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_quiz::CustomActionMsgGoal_<ContainerAllocator1> & lhs, const ::action_quiz::CustomActionMsgGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_quiz

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_quiz::CustomActionMsgGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_quiz::CustomActionMsgGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_quiz::CustomActionMsgGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_quiz::CustomActionMsgGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_quiz::CustomActionMsgGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_quiz::CustomActionMsgGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_quiz::CustomActionMsgGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e8c62b390dd09eb60220ad7325cbdf7";
  }

  static const char* value(const ::action_quiz::CustomActionMsgGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e8c62b390dd09ebULL;
  static const uint64_t static_value2 = 0x60220ad7325cbdf7ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_quiz::CustomActionMsgGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_quiz/CustomActionMsgGoal";
  }

  static const char* value(const ::action_quiz::CustomActionMsgGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_quiz::CustomActionMsgGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string goal\n"
;
  }

  static const char* value(const ::action_quiz::CustomActionMsgGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_quiz::CustomActionMsgGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomActionMsgGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_quiz::CustomActionMsgGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_quiz::CustomActionMsgGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_QUIZ_MESSAGE_CUSTOMACTIONMSGGOAL_H
