// Auto-generated. Do not edit!

// (in-package my_custom_action_message.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CustomFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.return_value = null;
    }
    else {
      if (initObj.hasOwnProperty('return_value')) {
        this.return_value = initObj.return_value
      }
      else {
        this.return_value = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CustomFeedback
    // Serialize message field [return_value]
    bufferOffset = _serializer.float32(obj.return_value, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CustomFeedback
    let len;
    let data = new CustomFeedback(null);
    // Deserialize message field [return_value]
    data.return_value = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_custom_action_message/CustomFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9ad3a54690081d42d1aba5dbffa1b504';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    float32 return_value
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CustomFeedback(null);
    if (msg.return_value !== undefined) {
      resolved.return_value = msg.return_value;
    }
    else {
      resolved.return_value = 0.0
    }

    return resolved;
    }
};

module.exports = CustomFeedback;
