// Auto-generated. Do not edit!

// (in-package my_custom_action_message.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class CustomResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.random_num = null;
    }
    else {
      if (initObj.hasOwnProperty('random_num')) {
        this.random_num = initObj.random_num
      }
      else {
        this.random_num = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CustomResult
    // Serialize message field [random_num]
    bufferOffset = _serializer.float32(obj.random_num, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CustomResult
    let len;
    let data = new CustomResult(null);
    // Deserialize message field [random_num]
    data.random_num = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_custom_action_message/CustomResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '4176a749b1704bf728d01e1708640142';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result
    float32 random_num
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CustomResult(null);
    if (msg.random_num !== undefined) {
      resolved.random_num = msg.random_num;
    }
    else {
      resolved.random_num = 0.0
    }

    return resolved;
    }
};

module.exports = CustomResult;
