(cl:defpackage my_custom_action_message-msg
  (:use )
  (:export
   "<CUSTOMACTION>"
   "CUSTOMACTION"
   "<CUSTOMACTIONFEEDBACK>"
   "CUSTOMACTIONFEEDBACK"
   "<CUSTOMACTIONGOAL>"
   "CUSTOMACTIONGOAL"
   "<CUSTOMACTIONRESULT>"
   "CUSTOMACTIONRESULT"
   "<CUSTOMFEEDBACK>"
   "CUSTOMFEEDBACK"
   "<CUSTOMGOAL>"
   "CUSTOMGOAL"
   "<CUSTOMRESULT>"
   "CUSTOMRESULT"
  ))

