; Auto-generated. Do not edit!


(cl:in-package my_custom_action_message-msg)


;//! \htmlinclude CustomFeedback.msg.html

(cl:defclass <CustomFeedback> (roslisp-msg-protocol:ros-message)
  ((return_value
    :reader return_value
    :initarg :return_value
    :type cl:float
    :initform 0.0))
)

(cl:defclass CustomFeedback (<CustomFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CustomFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CustomFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_custom_action_message-msg:<CustomFeedback> is deprecated: use my_custom_action_message-msg:CustomFeedback instead.")))

(cl:ensure-generic-function 'return_value-val :lambda-list '(m))
(cl:defmethod return_value-val ((m <CustomFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_custom_action_message-msg:return_value-val is deprecated.  Use my_custom_action_message-msg:return_value instead.")
  (return_value m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CustomFeedback>) ostream)
  "Serializes a message object of type '<CustomFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'return_value))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CustomFeedback>) istream)
  "Deserializes a message object of type '<CustomFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'return_value) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CustomFeedback>)))
  "Returns string type for a message object of type '<CustomFeedback>"
  "my_custom_action_message/CustomFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CustomFeedback)))
  "Returns string type for a message object of type 'CustomFeedback"
  "my_custom_action_message/CustomFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CustomFeedback>)))
  "Returns md5sum for a message object of type '<CustomFeedback>"
  "9ad3a54690081d42d1aba5dbffa1b504")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CustomFeedback)))
  "Returns md5sum for a message object of type 'CustomFeedback"
  "9ad3a54690081d42d1aba5dbffa1b504")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CustomFeedback>)))
  "Returns full string definition for message of type '<CustomFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 return_value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CustomFeedback)))
  "Returns full string definition for message of type 'CustomFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 return_value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CustomFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CustomFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CustomFeedback
    (cl:cons ':return_value (return_value msg))
))
