; Auto-generated. Do not edit!


(cl:in-package my_custom_action_message-msg)


;//! \htmlinclude CustomGoal.msg.html

(cl:defclass <CustomGoal> (roslisp-msg-protocol:ros-message)
  ((number
    :reader number
    :initarg :number
    :type cl:integer
    :initform 0))
)

(cl:defclass CustomGoal (<CustomGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CustomGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CustomGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_custom_action_message-msg:<CustomGoal> is deprecated: use my_custom_action_message-msg:CustomGoal instead.")))

(cl:ensure-generic-function 'number-val :lambda-list '(m))
(cl:defmethod number-val ((m <CustomGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_custom_action_message-msg:number-val is deprecated.  Use my_custom_action_message-msg:number instead.")
  (number m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CustomGoal>) ostream)
  "Serializes a message object of type '<CustomGoal>"
  (cl:let* ((signed (cl:slot-value msg 'number)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CustomGoal>) istream)
  "Deserializes a message object of type '<CustomGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'number) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CustomGoal>)))
  "Returns string type for a message object of type '<CustomGoal>"
  "my_custom_action_message/CustomGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CustomGoal)))
  "Returns string type for a message object of type 'CustomGoal"
  "my_custom_action_message/CustomGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CustomGoal>)))
  "Returns md5sum for a message object of type '<CustomGoal>"
  "2474488a3908093ec1307bdd5b35815e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CustomGoal)))
  "Returns md5sum for a message object of type 'CustomGoal"
  "2474488a3908093ec1307bdd5b35815e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CustomGoal>)))
  "Returns full string definition for message of type '<CustomGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%int32 number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CustomGoal)))
  "Returns full string definition for message of type 'CustomGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%int32 number~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CustomGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CustomGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CustomGoal
    (cl:cons ':number (number msg))
))
