; Auto-generated. Do not edit!


(cl:in-package my_custom_action_message-msg)


;//! \htmlinclude CustomResult.msg.html

(cl:defclass <CustomResult> (roslisp-msg-protocol:ros-message)
  ((random_num
    :reader random_num
    :initarg :random_num
    :type cl:float
    :initform 0.0))
)

(cl:defclass CustomResult (<CustomResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CustomResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CustomResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_custom_action_message-msg:<CustomResult> is deprecated: use my_custom_action_message-msg:CustomResult instead.")))

(cl:ensure-generic-function 'random_num-val :lambda-list '(m))
(cl:defmethod random_num-val ((m <CustomResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_custom_action_message-msg:random_num-val is deprecated.  Use my_custom_action_message-msg:random_num instead.")
  (random_num m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CustomResult>) ostream)
  "Serializes a message object of type '<CustomResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'random_num))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CustomResult>) istream)
  "Deserializes a message object of type '<CustomResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'random_num) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CustomResult>)))
  "Returns string type for a message object of type '<CustomResult>"
  "my_custom_action_message/CustomResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CustomResult)))
  "Returns string type for a message object of type 'CustomResult"
  "my_custom_action_message/CustomResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CustomResult>)))
  "Returns md5sum for a message object of type '<CustomResult>"
  "4176a749b1704bf728d01e1708640142")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CustomResult)))
  "Returns md5sum for a message object of type 'CustomResult"
  "4176a749b1704bf728d01e1708640142")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CustomResult>)))
  "Returns full string definition for message of type '<CustomResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%float32 random_num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CustomResult)))
  "Returns full string definition for message of type 'CustomResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%float32 random_num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CustomResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CustomResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CustomResult
    (cl:cons ':random_num (random_num msg))
))
