(cl:defpackage my_custom_srv_msg_pkg-srv
  (:use )
  (:export
   "MYCUSTOMSERVICEMESSAGE"
   "<MYCUSTOMSERVICEMESSAGE-REQUEST>"
   "MYCUSTOMSERVICEMESSAGE-REQUEST"
   "<MYCUSTOMSERVICEMESSAGE-RESPONSE>"
   "MYCUSTOMSERVICEMESSAGE-RESPONSE"
  ))

