// Generated by gencpp from file services_quiz/BB8CustomServiceMessage.msg
// DO NOT EDIT!


#ifndef SERVICES_QUIZ_MESSAGE_BB8CUSTOMSERVICEMESSAGE_H
#define SERVICES_QUIZ_MESSAGE_BB8CUSTOMSERVICEMESSAGE_H

#include <ros/service_traits.h>


#include <services_quiz/BB8CustomServiceMessageRequest.h>
#include <services_quiz/BB8CustomServiceMessageResponse.h>


namespace services_quiz
{

struct BB8CustomServiceMessage
{

typedef BB8CustomServiceMessageRequest Request;
typedef BB8CustomServiceMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BB8CustomServiceMessage
} // namespace services_quiz


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::services_quiz::BB8CustomServiceMessage > {
  static const char* value()
  {
    return "b78c0d1a37ffcec6adef7714dda05daa";
  }

  static const char* value(const ::services_quiz::BB8CustomServiceMessage&) { return value(); }
};

template<>
struct DataType< ::services_quiz::BB8CustomServiceMessage > {
  static const char* value()
  {
    return "services_quiz/BB8CustomServiceMessage";
  }

  static const char* value(const ::services_quiz::BB8CustomServiceMessage&) { return value(); }
};


// service_traits::MD5Sum< ::services_quiz::BB8CustomServiceMessageRequest> should match
// service_traits::MD5Sum< ::services_quiz::BB8CustomServiceMessage >
template<>
struct MD5Sum< ::services_quiz::BB8CustomServiceMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::services_quiz::BB8CustomServiceMessage >::value();
  }
  static const char* value(const ::services_quiz::BB8CustomServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::services_quiz::BB8CustomServiceMessageRequest> should match
// service_traits::DataType< ::services_quiz::BB8CustomServiceMessage >
template<>
struct DataType< ::services_quiz::BB8CustomServiceMessageRequest>
{
  static const char* value()
  {
    return DataType< ::services_quiz::BB8CustomServiceMessage >::value();
  }
  static const char* value(const ::services_quiz::BB8CustomServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::services_quiz::BB8CustomServiceMessageResponse> should match
// service_traits::MD5Sum< ::services_quiz::BB8CustomServiceMessage >
template<>
struct MD5Sum< ::services_quiz::BB8CustomServiceMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::services_quiz::BB8CustomServiceMessage >::value();
  }
  static const char* value(const ::services_quiz::BB8CustomServiceMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::services_quiz::BB8CustomServiceMessageResponse> should match
// service_traits::DataType< ::services_quiz::BB8CustomServiceMessage >
template<>
struct DataType< ::services_quiz::BB8CustomServiceMessageResponse>
{
  static const char* value()
  {
    return DataType< ::services_quiz::BB8CustomServiceMessage >::value();
  }
  static const char* value(const ::services_quiz::BB8CustomServiceMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICES_QUIZ_MESSAGE_BB8CUSTOMSERVICEMESSAGE_H
