// Generated by gencpp from file my_custom_action_message/CustomResult.msg
// DO NOT EDIT!


#ifndef MY_CUSTOM_ACTION_MESSAGE_MESSAGE_CUSTOMRESULT_H
#define MY_CUSTOM_ACTION_MESSAGE_MESSAGE_CUSTOMRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_custom_action_message
{
template <class ContainerAllocator>
struct CustomResult_
{
  typedef CustomResult_<ContainerAllocator> Type;

  CustomResult_()
    : random_num(0.0)  {
    }
  CustomResult_(const ContainerAllocator& _alloc)
    : random_num(0.0)  {
  (void)_alloc;
    }



   typedef float _random_num_type;
  _random_num_type random_num;





  typedef boost::shared_ptr< ::my_custom_action_message::CustomResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_custom_action_message::CustomResult_<ContainerAllocator> const> ConstPtr;

}; // struct CustomResult_

typedef ::my_custom_action_message::CustomResult_<std::allocator<void> > CustomResult;

typedef boost::shared_ptr< ::my_custom_action_message::CustomResult > CustomResultPtr;
typedef boost::shared_ptr< ::my_custom_action_message::CustomResult const> CustomResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_custom_action_message::CustomResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_custom_action_message::CustomResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_custom_action_message::CustomResult_<ContainerAllocator1> & lhs, const ::my_custom_action_message::CustomResult_<ContainerAllocator2> & rhs)
{
  return lhs.random_num == rhs.random_num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_custom_action_message::CustomResult_<ContainerAllocator1> & lhs, const ::my_custom_action_message::CustomResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_custom_action_message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_custom_action_message::CustomResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_custom_action_message::CustomResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_action_message::CustomResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_action_message::CustomResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_action_message::CustomResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_action_message::CustomResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_custom_action_message::CustomResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4176a749b1704bf728d01e1708640142";
  }

  static const char* value(const ::my_custom_action_message::CustomResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4176a749b1704bf7ULL;
  static const uint64_t static_value2 = 0x28d01e1708640142ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_custom_action_message::CustomResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_custom_action_message/CustomResult";
  }

  static const char* value(const ::my_custom_action_message::CustomResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_custom_action_message::CustomResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result\n"
"float32 random_num\n"
;
  }

  static const char* value(const ::my_custom_action_message::CustomResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_custom_action_message::CustomResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.random_num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_custom_action_message::CustomResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_custom_action_message::CustomResult_<ContainerAllocator>& v)
  {
    s << indent << "random_num: ";
    Printer<float>::stream(s, indent + "  ", v.random_num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CUSTOM_ACTION_MESSAGE_MESSAGE_CUSTOMRESULT_H
