// Generated by gencpp from file my_custom_action_message/CustomFeedback.msg
// DO NOT EDIT!


#ifndef MY_CUSTOM_ACTION_MESSAGE_MESSAGE_CUSTOMFEEDBACK_H
#define MY_CUSTOM_ACTION_MESSAGE_MESSAGE_CUSTOMFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_custom_action_message
{
template <class ContainerAllocator>
struct CustomFeedback_
{
  typedef CustomFeedback_<ContainerAllocator> Type;

  CustomFeedback_()
    : return_value(0.0)  {
    }
  CustomFeedback_(const ContainerAllocator& _alloc)
    : return_value(0.0)  {
  (void)_alloc;
    }



   typedef float _return_value_type;
  _return_value_type return_value;





  typedef boost::shared_ptr< ::my_custom_action_message::CustomFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_custom_action_message::CustomFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct CustomFeedback_

typedef ::my_custom_action_message::CustomFeedback_<std::allocator<void> > CustomFeedback;

typedef boost::shared_ptr< ::my_custom_action_message::CustomFeedback > CustomFeedbackPtr;
typedef boost::shared_ptr< ::my_custom_action_message::CustomFeedback const> CustomFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_custom_action_message::CustomFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_custom_action_message::CustomFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_custom_action_message::CustomFeedback_<ContainerAllocator1> & lhs, const ::my_custom_action_message::CustomFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.return_value == rhs.return_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_custom_action_message::CustomFeedback_<ContainerAllocator1> & lhs, const ::my_custom_action_message::CustomFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_custom_action_message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_custom_action_message::CustomFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_custom_action_message::CustomFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_action_message::CustomFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_custom_action_message::CustomFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_action_message::CustomFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_custom_action_message::CustomFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_custom_action_message::CustomFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ad3a54690081d42d1aba5dbffa1b504";
  }

  static const char* value(const ::my_custom_action_message::CustomFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ad3a54690081d42ULL;
  static const uint64_t static_value2 = 0xd1aba5dbffa1b504ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_custom_action_message::CustomFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_custom_action_message/CustomFeedback";
  }

  static const char* value(const ::my_custom_action_message::CustomFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_custom_action_message::CustomFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float32 return_value\n"
;
  }

  static const char* value(const ::my_custom_action_message::CustomFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_custom_action_message::CustomFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.return_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_custom_action_message::CustomFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_custom_action_message::CustomFeedback_<ContainerAllocator>& v)
  {
    s << indent << "return_value: ";
    Printer<float>::stream(s, indent + "  ", v.return_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CUSTOM_ACTION_MESSAGE_MESSAGE_CUSTOMFEEDBACK_H
