; Auto-generated. Do not edit!


(cl:in-package action_quiz-msg)


;//! \htmlinclude CustomActionMsgResult.msg.html

(cl:defclass <CustomActionMsgResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass CustomActionMsgResult (<CustomActionMsgResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CustomActionMsgResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CustomActionMsgResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_quiz-msg:<CustomActionMsgResult> is deprecated: use action_quiz-msg:CustomActionMsgResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CustomActionMsgResult>) ostream)
  "Serializes a message object of type '<CustomActionMsgResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CustomActionMsgResult>) istream)
  "Deserializes a message object of type '<CustomActionMsgResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CustomActionMsgResult>)))
  "Returns string type for a message object of type '<CustomActionMsgResult>"
  "action_quiz/CustomActionMsgResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CustomActionMsgResult)))
  "Returns string type for a message object of type 'CustomActionMsgResult"
  "action_quiz/CustomActionMsgResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CustomActionMsgResult>)))
  "Returns md5sum for a message object of type '<CustomActionMsgResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CustomActionMsgResult)))
  "Returns md5sum for a message object of type 'CustomActionMsgResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CustomActionMsgResult>)))
  "Returns full string definition for message of type '<CustomActionMsgResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CustomActionMsgResult)))
  "Returns full string definition for message of type 'CustomActionMsgResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CustomActionMsgResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CustomActionMsgResult>))
  "Converts a ROS message object to a list"
  (cl:list 'CustomActionMsgResult
))
