; Auto-generated. Do not edit!


(cl:in-package action_quiz-msg)


;//! \htmlinclude CustomActionMsgActionGoal.msg.html

(cl:defclass <CustomActionMsgActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type action_quiz-msg:CustomActionMsgGoal
    :initform (cl:make-instance 'action_quiz-msg:CustomActionMsgGoal)))
)

(cl:defclass CustomActionMsgActionGoal (<CustomActionMsgActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CustomActionMsgActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CustomActionMsgActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action_quiz-msg:<CustomActionMsgActionGoal> is deprecated: use action_quiz-msg:CustomActionMsgActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <CustomActionMsgActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_quiz-msg:header-val is deprecated.  Use action_quiz-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <CustomActionMsgActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_quiz-msg:goal_id-val is deprecated.  Use action_quiz-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <CustomActionMsgActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action_quiz-msg:goal-val is deprecated.  Use action_quiz-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CustomActionMsgActionGoal>) ostream)
  "Serializes a message object of type '<CustomActionMsgActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CustomActionMsgActionGoal>) istream)
  "Deserializes a message object of type '<CustomActionMsgActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CustomActionMsgActionGoal>)))
  "Returns string type for a message object of type '<CustomActionMsgActionGoal>"
  "action_quiz/CustomActionMsgActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CustomActionMsgActionGoal)))
  "Returns string type for a message object of type 'CustomActionMsgActionGoal"
  "action_quiz/CustomActionMsgActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CustomActionMsgActionGoal>)))
  "Returns md5sum for a message object of type '<CustomActionMsgActionGoal>"
  "c0da3d752463f5a611d8c6b55afc649f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CustomActionMsgActionGoal)))
  "Returns md5sum for a message object of type 'CustomActionMsgActionGoal"
  "c0da3d752463f5a611d8c6b55afc649f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CustomActionMsgActionGoal>)))
  "Returns full string definition for message of type '<CustomActionMsgActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%CustomActionMsgGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: action_quiz/CustomActionMsgGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CustomActionMsgActionGoal)))
  "Returns full string definition for message of type 'CustomActionMsgActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%CustomActionMsgGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: action_quiz/CustomActionMsgGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CustomActionMsgActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CustomActionMsgActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CustomActionMsgActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
